# -*- coding: utf-8 -*-
"""Financode_Copia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kbl8dVkl6STALcfjNtqh733_bRoxJYHs
"""

# Proyecto: Financode
# Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez
# Descripción: App que determina el perfil del inversor y analiza acciones con Python.

# pip install streamlit yfinance

# pip install streamlit-option-menu

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import datetime
import plotly.graph_objects as go
import altair as alt # Necesario para la gráfica avanzada de riesgo-retorno

# --- CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="FinanCode",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- IMPORTANTE: INICIALIZACIÓN DE st.session_state ---
if 'perfil' not in st.session_state:
    st.session_state.perfil = None

# --- BARRA LATERAL (SIDEBAR) ---
with st.sidebar:
    st.title("FinanCode 1.0")
    seleccion = st.radio(
        "Menú de navegación",
        ["Inicio", "Perfil de inversor", "Análisis de Portafolio", "Configuración"],
        captions=[
            "Bienvenida",
            "Define tu tolerancia al riesgo",
            "Simula tu portafolio",
            "Ajustes de la app"
        ]
    )
    st.markdown("---")
    st.markdown("*Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez*")


# --- DEFINICIÓN DE FUNCIONES DE CÁLCULO ---

def get_data(tickers, start_date, end_date, benchmark_ticker="^GSPC"):
    """
    Descarga datos de precios de CIERRE (Close).
    Se asegura de que tanto asset_data como benchmark_data sean DataFrames.
    """
    all_tickers = tickers + [benchmark_ticker]
    # Usando 'Close' como se solicitó
    data = yf.download(all_tickers, start=start_date, end=end_date)['Close']
    
    if isinstance(data, pd.Series):
        data = data.to_frame(name=all_tickers[0])

    # Usando corchetes dobles para mantener el formato DataFrame
    benchmark_data = data[[benchmark_ticker]].dropna()
    asset_data = data[tickers].dropna()
    
    return asset_data, benchmark_data

def calculate_beta(asset_returns, benchmark_returns):
    """Calcula beta para cada activo contra el benchmark."""
    betas = {}
    
    bench_series = benchmark_returns.iloc[:, 0]
    aligned_assets, aligned_bench = asset_returns.align(bench_series, join='inner', axis=0)

    if aligned_assets.empty:
        return {col: np.nan for col in asset_returns.columns}

    benchmark_variance = aligned_bench.var()
    
    if benchmark_variance == 0:
        return {col: np.nan for col in asset_returns.columns}

    for column in aligned_assets.columns:
        covariance = aligned_assets[column].cov(aligned_bench)
        beta = covariance / benchmark_variance
        betas[column] = beta
    return betas

# --- CONTENIDO DINÁMICO ---
if seleccion == "Inicio":
    st.title("💰 Bienvenido a FinanCode")
    st.header("✨ Tu estilo, tu riesgo, tu inversión.")
    st.markdown("""
    Esta app te ayuda a identificar tu *perfil de inversor* y analizar el comportamiento de un portafolio de acciones reales, 
    cumpliendo con los requisitos clave del análisis financiero.
    """)
    
    st.subheader("Requisitos Cumplidos (según especificaciones):")
    
    col_req1, col_req2 = st.columns(2)
    
    with col_req1:
        st.markdown("""
        #### 1. Entradas de Usuario
        * **✅ Selección de empresas:** Ingresa múltiples tickers (ej: AAPL, MSFT).
        * **✅ Pesos del portafolio:** Asigna un peso porcentual a cada activo.
        * **✅ Inversión inicial:** Define el monto monetario para la simulación.
        * **✅ Periodo de análisis:** Selecciona fecha de inicio y fin.
        * **✅ Tasa Libre de Riesgo:** Ajusta el 'Risk-Free Rate' para el Sharpe Ratio.

        #### 2. Visualizaciones
        * **✅ Serie de tiempo de precios:** Gráfico de precios normalizados.
        * **✅ Retornos acumulados:** Gráfico de retornos acumulados del portafolio.
        * **✅ Evolución del valor monetario:** Gráfico del valor de tu inversión.
        * **✅ Diagrama riesgo-retorno:** Compara activos vs. portafolio.
        * **✅ Benchmark (Opcional):** Métricas Beta vs. S&P 500.
        """)
        
    with col_req2:
        st.markdown("""
        #### 3. Resultados Mínimos
        * **✅ Retornos por periodo y acumulados:** Calculados para el portafolio.
        * **✅ Volatilidad histórica y anualizada:** Calculada para el portafolio.
        * **✅ Sharpe ratio:** Calculado para el portafolio.
        * **✅ Evolución del valor monetario:** Mostrado en métrica y gráfico.

        #### 4. Fuente de Datos y Lenguaje
