# -*- coding: utf-8 -*-
"""Financode_Copia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kbl8dVkl6STALcfjNtqh733_bRoxJYHs
"""

# Proyecto: Financode
# Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez
# Descripción: App que determina el perfil del inversor y analiza acciones con Python.

# pip install streamlit yfinance

# pip install streamlit-option-menu

# Importar librerias ----
import streamlit as st #Interfaz intercativo
import pandas as pd #Manejo de dataframes
import numpy as np #Soporte de cálculo matemáticos y matrices
import yfinance as yf #Datos financieros de Yahoo Finance
import matplotlib.pyplot as plt #Gráficos y visualizaciones de datos
import datetime #Manejo de fechas
from streamlit_option_menu import option_menu

# Inicializar variable de sesión ---
if "perfil" not in st.session_state:
    st.session_state.perfil = None

# Crear menú lateral
with st.sidebar:
    seleccion = option_menu(
        "FinanCode",
        ["Inicio", "Perfil de inversor", "Simulación de portafolio: Una acción", "Simulación de portafolio: Dos o más acciones", "Referencias"],
        icons=["house", "graph-up", "bar-chart", "gear"],
        menu_icon="cast",
        default_index=0,
        orientation="vertical",
    )

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import datetime
import plotly.graph_objects as go 
# Usaremos Plotly para mejores gráficos

# --- CONFIGURACIÓN DE PÁGINA ---
# (Asegúrate de que esta sea la primera comando de Streamlit)
st.set_page_config(
    page_title="FinanCode",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- IMPORTANTE: INICIALIZACIÓN DE st.session_state ---
# Esto es crucial para que la app funcione entre pestañas
if 'perfil' not in st.session_state:
    st.session_state.perfil = None

# --- BARRA LATERAL (SIDEBAR) ---
with st.sidebar:
    st.title("FinanCode 1.0")
    seleccion = st.radio(
        "Menú de navegación",
        ["Inicio", "Perfil de inversor", "Análisis de Portafolio", "Configuración"],
        captions=[
            "Bienvenida",
            "Define tu tolerancia al riesgo",
            "Simula tu portafolio",
            "Ajustes de la app"
        ]
    )
    st.markdown("---")
    st.markdown("*Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez*")


# --- CONTENIDO DINÁMICO ---
if seleccion == "Inicio":
    st.title("💰 Bienvenido a FinanCode")
    st.header("✨ Tu estilo, tu riesgo, tu inversión.")
    st.markdown("""
    Esta app te ayuda a identificar tu *perfil de inversor* y analizar el comportamiento de un portafolio de acciones reales,
    cumpliendo con los requisitos clave del análisis financiero.
    """)

    st.subheader("Requisitos Cumplidos (según especificaciones):")

    col_req1, col_req2 = st.columns(2)

    with col_req1:
        st.markdown("""
        #### 1. Entradas de Usuario
        *   **✅ Selección de empresas:** Ingresa múltiples tickers (ej: AAPL, MSFT).
        *   **✅ Pesos del portafolio:** Asigna un peso porcentual a cada activo.
        *   **✅ Inversión inicial:** Define el monto monetario para la simulación.
        *   **✅ Periodo de análisis:** Selecciona fecha de inicio y fin.
        *   **✅ Tasa Libre de Riesgo:** Ajusta el 'Risk-Free Rate' para el Sharpe Ratio.

        #### 2. Visualizaciones
        *   **✅ Serie de tiempo de precios:** Gráfico de precios normalizados.
        *   **✅ Retornos acumulados:** Gráfico de retornos acumulados del portafolio.
        *   **✅ Evolución del valor monetario:** Gráfico del valor de tu inversión.
        *   **✅ Diagrama riesgo-retorno:** Compara activos vs. portafolio.
        *   **✅ Benchmark (Opcional):** Métricas Beta vs. S&P 500.
        """)

    with col_req2:
        st.markdown("""
        #### 3. Resultados Mínimos
        *   **✅ Retornos por periodo y acumulados:** Calculados para el portafolio.
        *   **✅ Volatilidad histórica y anualizada:** Calculada para el portafolio.
        *   **✅ Sharpe ratio:** Calculado para el portafolio.
        *   **✅ Evolución del valor monetario:** Mostrado en métrica y gráfico.

        #### 4. Fuente de Datos y Lenguaje
        *   **✅ Lenguaje:** Python (Streamlit).
        *   **✅ Fuente de datos:** API de Yahoo Finance (`yfinance`).
        """)

elif seleccion == "Perfil de inversor":

    # 🧭 CUESTIONARIO DE PERFIL
    st.title("🧩 Cuestionario del inversor")
    st.header("👤 Descubre tu perfil de inversor")
    st.markdown("Responde las siguientes preguntas para determinar tu tolerancia al riesgo, horizonte y conocimiento.")
    st.markdown("---")

    puntaje_total = 0

    # --- SECCIÓN I: TOLERANCIA AL RIESGO ---
    st.subheader("I. Tolerancia al riesgo (Tu reacción a la volatilidad)")

    q1 = st.radio(
        "1. Si tus acciones cayeran un 20% en un mes, tú...",
        [
            "Venderías todo para evitar más pérdidas.",
            "Mantendrías la posición esperando la recuperación.",
            "Aumentarías tu inversión aprovechando los precios bajos."
        ],
        index=None
    )
    if q1:
        puntaje_total += [1, 3, 5][["Venderías" in q1, "Mantendrías" in q1, "Aumentarías" in q1].index(True)]

    q2 = st.radio(
        "2. ¿Qué priorizas al invertir?",
        [
            "Seguridad y estabilidad del capital.",
            "Equilibrio entre crecimiento y seguridad.",
            "Rendimiento alto, aceptando fluctuaciones fuertes."
        ],
        index=None
    )
    if q2:
        puntaje_total += [1, 3, 5][["Seguridad" in q2, "Equilibrio" in q2, "Rendimiento" in q2].index(True)]

    q3 = st.radio(
        "3. ¿Qué nivel de caída podrías tolerar en un año?",
        [
            "Hasta 5%. Prefiero estabilidad.",
            "Entre 10% y 20%. Entiendo que los mercados bajan.",
            "Más del 25%. Asumo riesgos para buscar mayores retornos."
        ],
        index=None
    )
    if q3:
        puntaje_total += [1, 3, 5][["5%" in q3, "10%" in q3, "25%" in q3].index(True)]

    st.markdown("---")

    # --- SECCIÓN II: HORIZONTE DE INVERSIÓN ---
    st.subheader("II. Horizonte de inversión (Plazo)")

    q4 = st.radio(
        "4. ¿Con qué objetivo inviertes principalmente?",
        [
            "Necesidades o gastos en el corto plazo (1 a 3 años).",
            "Ahorros para metas en el mediano plazo (3 a 7 años).",
            "Construir patrimonio o jubilación (más de 7 años)."
        ],
        index=None
    )
    if q4:
        puntaje_total += [1, 3, 5][["corto" in q4, "mediano" in q4, "largo" in q4 or "más" in q4].index(True)]

    q5 = st.radio(
        "5. ¿Cuándo esperas usar la mayoría de tu capital invertido?",
        [
            "Antes de 2 años.",
            "En 5 a 10 años.",
            "En más de 15 años."
        ],
        index=None
    )
    if q5:
        puntaje_total += [1, 3, 5][["Antes" in q5, "5 a 10" in q5, "15" in q5].index(True)]

    st.markdown("---")

    # --- SECCIÓN III: CONOCIMIENTO Y EXPERIENCIA ---
    st.subheader("III. Conocimiento y experiencia")

    q6 = st.radio(
        "6. ¿Qué tan familiarizado estás con indicadores como el Ratio de Sharpe o el modelo CAPM?",
        [
            "No los conozco.",
            "He escuchado de ellos y entiendo lo básico.",
            "Los uso en mis análisis o estudios financieros."
        ],
        index=None
    )
    if q6:
        puntaje_total += [1, 3, 5][["No los conozco" in q6, "básico" in q6, "uso" in q6].index(True)]

    q7 = st.radio(
        "7. ¿En qué tipo de activos sueles invertir o analizar?",
        [
            "Solo cuentas de ahorro o fondos conservadores.",
            "Acciones y bonos. Conozco los riesgos del mercado.",
            "Acciones, derivados o criptomonedas. Manejo portafolios activos."
        ],
        index=None
    )
    if q7:
        puntaje_total += [1, 3, 5][["ahorro" in q7, "Acciones y bonos" in q7, "criptomonedas" in q7].index(True)]

    st.markdown("---")

    # --- RESULTADO ---
    preguntas_respondidas = all([q1, q2, q3, q4, q5, q6, q7])

    if st.button("Calcular mi perfil de inversión"):
        if preguntas_respondidas:
            st.subheader("🎯 Resultado de tu perfil de inversión en acciones")
            st.metric("Puntuación Total", puntaje_total)

            if puntaje_total <= 15:
                perfil = "Conservador 🛡️"
                st.success(f"Tu perfil es: **{perfil}**")
                st.write("Prefieres estabilidad. Te convienen acciones de empresas grandes y consolidadas.")
                st.session_state.perfil = "CONSERVADOR"

            elif puntaje_total <= 25:
                perfil = "Moderado 🌿"
                st.info(f"Tu perfil es: **{perfil}**")
                st.write("Buscas equilibrio. Puedes combinar acciones consolidadas con sectores de crecimiento moderado.")
                st.session_state.perfil = "MODERADO"

            else:
                perfil = "Agresivo 🔥"
                st.warning(f"Tu perfil es: **{perfil}**")
                st.write("Tienes alta tolerancia al riesgo. Podrías enfocarte en acciones de alto crecimiento, emergentes o tecnología, usando análisis de Sharpe o CAPM.")
                st.session_state.perfil = "AGRESIVO"

        else:
            st.error("Por favor responde todas las preguntas antes de calcular tu perfil.")

elif seleccion == "Análisis de Portafolio":
    st.header("📈 Análisis y Simulación de Portafolio")

    if st.session_state.perfil is None:
        st.error("🛑 Por favor, completa el **Cuestionario del Inversor** en la pestaña anterior para desbloquear la simulación.")
    else:
        st.success(f"Perfil Actual: **{st.session_state.perfil}**. ¡Configura tu simulación!")
        st.markdown("---")

        # --- REQ 3: ENTRADAS MÍNIMAS ---

        # 1. Selección de empresas
        st.subheader("1. Selección de Activos")
        tickers_input = st.text_input(
            "Ingrese los Tickers separados por comas (ej: AAPL, MSFT, GOOG, MELI)",
            value="AAPL,MSFT,GOOG"
        )
        tickers = [t.strip().upper() for t in tickers_input.split(",") if t.strip()]

        # 2. Pesos del portafolio
        st.subheader("2. Asignación de Pesos (%)")
        pesos_pct = []
        if not tickers:
            st.warning("Por favor, ingrese al menos un ticker.")
        else:
            weight_cols = st.columns(len(tickers))
            default_weight = 100.0 / len(tickers)
            for i, ticker in enumerate(tickers):
                with weight_cols[i]:
                    peso_individual = st.number_input(
                        f"Peso % para {ticker}",
                        min_value=0.0,
                        max_value=100.0,
                        value=default_weight,
                        step=1.0,
                        format="%.2f"
                    )
                    pesos_pct.append(peso_individual)

            total_weight = sum(pesos_pct)
            if not np.isclose(total_weight, 100.0):
                st.error(f"El total de los pesos es {total_weight:.2f}%. Debe sumar 100%.")
            else:
                st.success(f"Pesos asignados correctamente. Total: {total_weight:.0f}%.")

        st.markdown("---")

        # 3. Inversión inicial, Periodo y Frecuencia (implícita)
        st.subheader("3. Configuración de Simulación")

        sim_col1, sim_col2 = st.columns(2)

        with sim_col1:
            # 3.a. Inversión inicial
            inversion_inicial = st.number_input(
                "Inversión Inicial ($)",
                min_value=1.0,
                value=10000.0,
                step=1000.0,
                help="Monto monetario inicial para la simulación."
            )

            # 3.b. Tasa Libre de Riesgo (para Sharpe)
            RF = st.number_input(
                "Tasa Libre de Riesgo (Anual)",
                min_value=0.0,
                max_value=1.0,
                value=0.04, # 4% por defecto
                step=0.005,
                format="%.3f",
                help="Tasa de referencia (ej: Bonos del Tesoro) para calcular el Ratio de Sharpe."
            )

        with sim_col2:
            # 3.c. Periodo de análisis
            today = datetime.date.today()
            three_years_ago = today - datetime.timedelta(days=3 * 365)

            d = st.date_input(
                "Seleccione el período histórico para el análisis",
                value=(three_years_ago, today),
                min_value=datetime.date(1990, 1, 1),
                max_value=today,
                format="YYYY-MM-DD",
            )

        start_date = d[0]
        end_date = d[1]

        # Benchmark Ticker (S&P 500)
        MARKET_TICKER = "^GSPC"

        st.markdown("---")

        # --- BOTÓN DE EJECUCIÓN ---
        if st.button("Ejecutar Análisis de Portafolio", type="primary"):

            # Validaciones de entrada
            if not tickers:
                st.error("Error: No se han ingresado tickers.")
            elif not np.isclose(sum(pesos_pct), 100.0):
                st.error("Error: Los pesos no suman 100%.")
            else:
                with st.spinner("Descargando datos y calculando métricas..."):

                    # Normalizar pesos a decimal
                    pesos = np.array(pesos_pct) / 100.0

                    # --- Definición de Funciones ---

                    def get_data(tickers, start_date, end_date, benchmark_ticker="^GSPC"):
                        """Descarga datos de precios de cierre ajustados."""
                        all_tickers = tickers + [benchmark_ticker]
                        data = yf.download(all_tickers, start=start_date, end=end_date)['Close']

                        # Manejar el caso de un solo ticker (devuelve Series)
                        if isinstance(data, pd.Series):
                            data = data.to_frame(name=all_tickers[0])

                        # Separar activos y benchmark
                        asset_data = data[tickers]
                        benchmark_data = data[benchmark_ticker].to_frame(name=benchmark_ticker)

                        # Manejar caso de un solo ticker en el portafolio
                        if len(tickers) == 1:
                            asset_data = asset_data.to_frame(name=tickers[0])

                        return asset_data.dropna(), benchmark_data.dropna()

                    def calculate_beta(asset_returns, benchmark_returns):
                        """Calcula beta para cada activo contra el benchmark."""
                        betas = {}
                        # Asegurar que benchmark_returns sea una Serie
                        bench_series = benchmark_returns.iloc[:, 0]

                        # Alineamos los índices por si acaso
                        aligned_assets, aligned_bench = asset_returns.align(bench_series, join='inner', axis=0)

                        if aligned_assets.empty:
                            return {col: np.nan for col in asset_returns.columns}

                        benchmark_variance = aligned_bench.var()

                        if benchmark_variance == 0:
                            return {col: np.nan for col in asset_returns.columns}

                        for column in aligned_assets.columns:
                            covariance = aligned_assets[column].cov(aligned_bench)
                            beta = covariance / benchmark_variance
                            betas[column] = beta
                        return betas

                    # --- Ejecución de Cálculos ---
                    try:
                        datos, benchmark_data = get_data(tickers, start_date, end_date, MARKET_TICKER)

                        if datos.empty:
                            st.error("No se pudieron descargar los datos. Revise los tickers o el rango de fechas.")

                        # --- CÁLCULOS INDIVIDUALES ---
                        retornos = datos.pct_change().dropna()
                        benchmark_retornos = benchmark_data.pct_change().dropna()

                        # Asegurar alineación de retornos
                        retornos_aligned, benchmark_retornos_aligned = retornos.align(benchmark_retornos.iloc[:, 0], join='inner', axis=0)

                        if retornos_aligned.empty:
                             st.error("No hay datos comunes entre los activos y el benchmark en el período seleccionado.")
                             st.stop()

                        benchmark_retornos_df = benchmark_retornos_aligned.to_frame(name=MARKET_TICKER)

                        retorno_anual_ind = retornos_aligned.mean() * 252
                        volatilidad_anual_ind = retornos_aligned.std() * np.sqrt(252)
                        sharpe_anual_ind = (retorno_anual_ind - RF) / volatilidad_anual_ind
                        matriz_cov = retornos_aligned.cov() * 252

                        # CAPM y Beta
                        betas = calculate_beta(retornos_aligned, benchmark_retornos_df)
                        Rm = benchmark_retornos_aligned.mean() * 252
                        retorno_capm_series = pd.Series({t: RF + beta * (Rm - RF) for t, beta in betas.items()})

                        # --- REQ 4: CÁLCULOS DE PORTAFOLIO ---
                        retorno_p = np.dot(pesos, retorno_anual_ind)
                        volatilidad_p = np.sqrt(np.dot(pesos.T, np.dot(matriz_cov, pesos)))
                        sharpe_p = (retorno_p - RF) / volatilidad_p

                        # Retornos diarios del portafolio
                        retornos_diarios_p = (retornos_aligned * pesos).sum(axis=1)

                        # Retornos acumulados del portafolio
                        retornos_acum_p = (1 + retornos_diarios_p).cumprod()

                        # Evolución monetaria
                        valor_portafolio = inversion_inicial * retornos_acum_p


                        # --- PRESENTACIÓN DE RESULTADOS ---

                        st.subheader("Resultados del Portafolio")
                        st.markdown(f"**Período:** {start_date.strftime('%Y-%m-%d')} a {end_date.strftime('%Y-%m-%d')}")

                        # --- REQ 4: RESULTADOS MÍNIMOS (MÉTRICAS) ---
                        res_col1, res_col2, res_col3, res_col4 = st.columns(4)
                        with res_col1:
                            st.metric("Valor Final ($)", f"${valor_portafolio.iloc[-1]:,.2f}")
                        with res_col2:
                            st.metric("Retorno Anualizado", f"{retorno_p*100:.2f}%")
                        with res_col3:
                            st.metric("Volatilidad Anualizada", f"{volatilidad_p*100:.2f}%")
                        with res_col4:
                            st.metric("Ratio de Sharpe", f"{sharpe_p:.2f}")

                        # --- REQ 5: VISUALIZACIONES MÍNIMAS ---

                        tab1, tab2, tab3 = st.tabs([
                            "📈 Evolución y Riesgo-Retorno",
                            "📊 Métricas Individuales (Benchmark)",
                            "📉 Precios Históricos"
                        ])

                        with tab1:
                            st.subheader("Evolución del Valor Monetario del Portafolio")
                            st.line_chart(valor_portafolio)

                            st.subheader("Retornos Acumulados del Portafolio")
                            st.line_chart(retornos_acum_p)

                            st.subheader("Diagrama Riesgo-Retorno")
                            # Crear DataFrame para el gráfico
                            df_riesgo_retorno = pd.DataFrame({
                                'Retorno': retorno_anual_ind,
                                'Volatilidad': volatilidad_anual_ind,
                                'Tipo': 'Activo Individual'
                            })
                            # Añadir datos del portafolio
                            df_riesgo_retorno.loc['Portafolio'] = {
                                'Retorno': retorno_p,
                                'Volatilidad': volatilidad_p,
                                'Tipo': 'Mi Portafolio'
                            }
                            df_riesgo_retorno = df_riesgo_retorno.reset_index().rename(columns={'index': 'Activo'})

                            # Gráfico de dispersión
                            st.scatter_chart(
                                df_riesgo_retorno,
                                x='Volatilidad',
                                y='Retorno',
                                color='Tipo',
                                size=60,
                                tooltip=['Activo', 'Volatilidad', 'Retorno']
                            )
                            st.caption("Nota: 'Mi Portafolio' muestra el riesgo y retorno combinados según los pesos asignados.")

                        with tab2:
                            st.subheader("Métricas Individuales de Activos (vs. Benchmark)")
                            metricas_df = pd.DataFrame({
                                'Peso Asignado': pd.Series(pesos, index=tickers).apply(lambda x: f"{x*100:.1f}%"),
                                'Retorno Anual (Histórico)': retorno_anual_ind.apply(lambda x: f"{x*100:.2f}%"),
                                'Retorno Esperado (CAPM)': retorno_capm_series.apply(lambda x: f"{x*100:.2f}%"),
                                'Volatilidad Anual (Riesgo)': volatilidad_anual_ind.apply(lambda x: f"{x*100:.2f}%"),
                                f'Beta (vs. {MARKET_TICKER})': pd.Series(betas).round(2),
                                'Ratio de Sharpe': sharpe_anual_ind.round(2)
                            })
                            st.dataframe(metricas_df, use_container_width=True)

                        with tab3:
                            st.subheader("Evolución Histórica de Precios (Normalizados)")
                            st.markdown("Precios ajustados, normalizados a 1 al inicio del período para comparar el crecimiento.")
                            datos_normalizados = datos / datos.iloc[0]
                            st.line_chart(datos_normalizados)


                    except Exception as e:
                        st.error(f"Ocurrió un error durante la simulación: {e}")
                        st.exception(e)


elif seleccion == "Configuración":
    st.header("⚙️ Configuración de usuario")
    st.write("Esta sección está reservada para futuras configuraciones, como guardar perfiles o cambiar temas.")
